#line 1 "beancount/parser/lexer.c"

#include "parser.h"

typedef struct _yyextra_t yyextra_t;

/**
 * Allocate a new scanner object including private data.
 *
 * This encapsulates the native yylex_init_extra() API.
 */
yyscan_t yylex_new(void);

/**
 * Free scanner object including private data.
 *
 * This encapsulated the native yylex_destroy() API. Python objects
 * references stored in the @scanner are decremented.
 */
yyscan_t yylex_free(yyscan_t scanner);

/**
 * Initialize scanner private data.
 *
 * Setup @scanner to read from the Python file-like object @file. Set
 * the reported file name to @filename, if not NULL and not None.
 * Otherwise try to obtain the file name from the @name attribute of
 * the @file object. If this fails, use the empty string. @encoding is
 * used to decode strings read from the input file, if not NULL,
 * otherwise the default UTF-8 encoding is used. Python objects
 * references are incremented. It is safe to call this multiple times.
 */
void yylex_initialize(PyObject* file, PyObject* filename, int lineno, const char* encoding, yyscan_t scanner);

#line 35 "beancount/parser/lexer.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

#ifdef yyget_lval
#define yyget_lval_ALREADY_DEFINED
#else
#define yyget_lval yyget_lval
#endif

#ifdef yyset_lval
#define yyset_lval_ALREADY_DEFINED
#else
#define yyset_lval yyset_lval
#endif

#ifdef yyget_lloc
#define yyget_lloc_ALREADY_DEFINED
#else
#define yyget_lloc yyget_lloc
#endif

#ifdef yyset_lloc
#define yyset_lloc_ALREADY_DEFINED
#else
#define yyset_lloc yyset_lloc
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* An opaque pointer. */
#ifndef YY_TYPEDEF_YY_SCANNER_T
#define YY_TYPEDEF_YY_SCANNER_T
typedef void* yyscan_t;
#endif

/* For convenience, these vars (plus the bison vars far below)
   are macros in the reentrant scanner. */
#define yyin yyg->yyin_r
#define yyout yyg->yyout_r
#define yyextra yyg->yyextra_r
#define yyleng yyg->yyleng_r
#define yytext yyg->yytext_r
#define yylineno (YY_CURRENT_BUFFER_LVALUE->yy_bs_lineno)
#define yycolumn (YY_CURRENT_BUFFER_LVALUE->yy_bs_column)
#define yy_flex_debug yyg->yy_flex_debug_r

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yyg->yy_start = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yyg->yy_start - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin , yyscanner )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = yyg->yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yyg->yy_c_buf_p = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, yyg->yytext_ptr , yyscanner )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( yyg->yy_buffer_stack \
                          ? yyg->yy_buffer_stack[yyg->yy_buffer_stack_top] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE yyg->yy_buffer_stack[yyg->yy_buffer_stack_top]

void yyrestart ( FILE *input_file , yyscan_t yyscanner );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer , yyscan_t yyscanner );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size , yyscan_t yyscanner );
void yy_delete_buffer ( YY_BUFFER_STATE b , yyscan_t yyscanner );
void yy_flush_buffer ( YY_BUFFER_STATE b , yyscan_t yyscanner );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer , yyscan_t yyscanner );
void yypop_buffer_state ( yyscan_t yyscanner );

static void yyensure_buffer_stack ( yyscan_t yyscanner );
static void yy_load_buffer_state ( yyscan_t yyscanner );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file , yyscan_t yyscanner );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER , yyscanner)

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size , yyscan_t yyscanner );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str , yyscan_t yyscanner );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len , yyscan_t yyscanner );

void *yyalloc ( yy_size_t , yyscan_t yyscanner );
void *yyrealloc ( void *, yy_size_t , yyscan_t yyscanner );
void yyfree ( void * , yyscan_t yyscanner );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap(yyscanner) (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

typedef int yy_state_type;

#define yytext_ptr yytext_r

static yy_state_type yy_get_previous_state ( yyscan_t yyscanner );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  , yyscan_t yyscanner);
static int yy_get_next_buffer ( yyscan_t yyscanner );
static void yynoreturn yy_fatal_error ( const char* msg , yyscan_t yyscanner );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yyg->yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yyg->yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yyg->yy_c_buf_p = yy_cp;
#define YY_NUM_RULES 57
#define YY_END_OF_BUFFER 58
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[348] =
    {   0,
        0,    0,    0,    0,   58,   55,    3,    1,   24,   55,
       21,   19,   20,   22,   16,   14,   17,   18,   51,   23,
        6,    9,   55,   24,   55,   55,   24,   55,   55,   55,
       55,   55,   55,   55,   55,   55,   55,   55,   55,   12,
        7,   13,   15,   55,   55,   55,   55,   55,   55,   55,
       55,    3,    5,    5,    4,    4,    5,    5,   56,   57,
        3,    0,   50,    0,   52,    0,   51,   51,    6,    8,
        0,    0,   49,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   49,   49,   49,   53,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,   10,   11,    0,    0,    0,    0,
        0,    0,    0,    0,    2,    3,    4,   56,   51,   51,
       51,    0,   49,    0,   49,   48,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   49,   49,   49,   54,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   30,    0,    0,    0,    0,
        0,   25,    0,    0,    0,   51,    0,   49,    0,   49,
       48,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   49,
       46,   44,    0,    0,    0,    0,    0,    0,    0,   35,

       27,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       51,    0,   49,    0,   49,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   45,    0,   28,    0,
        0,    0,   31,    0,    0,    0,    0,    0,   34,    0,
        0,   32,    0,    0,   49,    0,   49,    0,    0,    0,
       48,    0,    0,   33,    0,    0,   41,   42,    0,   38,
        0,    0,    0,    0,   49,    0,   49,   48,   26,    0,
        0,   43,   40,    0,   37,   47,    0,   49,    0,   49,
        0,   36,   39,    0,   49,    0,   49,   29,    0,   49,
        0,   49,    0,   49,    0,   49,    0,   49,    0,   49,

        0,   49,    0,   49,    0,   49,    0,   49,    0,   49,
        0,   49,    0,   49,    0,   49,    0,   49,    0,   49,
        0,   49,    0,   49,    0,   49,    0,   49,    0,   49,
        0,   49,    0,   49,    0,   49,    0,   49,    0,   49,
        0,   49,    0,   49,   49,   49,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    7,    1,    5,    5,    8,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   18,   19,    1,
        1,    1,    5,   20,   21,   22,   23,   22,   24,   25,
       22,   22,   22,   22,   22,   26,   23,   27,   22,   23,
       22,   28,   29,   30,   31,   22,   22,   22,   22,   22,
        1,   32,    1,   33,   34,    1,   35,   36,   37,   38,

       39,   40,   41,   42,   43,   40,   40,   44,   45,   46,
       47,   48,   49,   50,   51,   52,   53,   54,   40,   55,
       56,   40,   57,   58,   59,   60,    1,   61,   61,   61,
       61,   61,   61,   61,   61,   61,   61,   61,   61,   61,
       61,   61,   61,   62,   62,   62,   62,   62,   62,   62,
       62,   62,   62,   62,   62,   62,   62,   62,   62,   63,
       63,   63,   63,   63,   63,   63,   63,   63,   63,   63,
       63,   63,   63,   63,   63,   63,   63,   63,   63,   63,
       63,   63,   63,   63,   63,   63,   63,   63,   63,   63,
       63,    1,    1,   64,   64,   64,   64,   64,   64,   64,

       64,   64,   64,   64,   64,   64,   64,   64,   64,   64,
       64,   64,   64,   64,   64,   64,   64,   64,   64,   64,
       64,   64,   64,   65,   66,   66,   66,   66,   66,   66,
       66,   66,   66,   66,   66,   66,   67,   68,   68,   69,
       70,   70,   70,   71,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[72] =
    {   0,
        1,    2,    3,    2,    1,    1,    1,    4,    1,    1,
        1,    1,    1,    5,    6,    7,    8,    9,    1,    1,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    1,    1,   10,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,    1,    1,    1,    1,
        1,    1,    1,   12,   12,   12,   12,   12,   12,   12,
       12
    } ;

static const flex_int16_t yy_base[381] =
    {   0,
        0,   70,   76,   80,  815, 1528,   72, 1528, 1528,   79,
        0, 1528, 1528, 1528, 1528, 1528, 1528, 1528,   74, 1528,
        0,  789,  104,    0,  783,  772,  774,    0,    0,  766,
       50,  753,  743,  750,  748,  746,   60,  740,  730,  726,
     1528,  708, 1528,   53,  703,  100,   44,  103,   46,  115,
      704,   88, 1528,    0,    0,    0,    0,  735,    0, 1528,
      177,  161, 1528,  755,    0,  107,  740,  167,    0, 1528,
      175,  202,    0,  130,  229,  124,  693,  141,   75,  144,
      129,  150,  679,  713,  712,  705,    0,  713,  170,   55,
       78,  190,  197,  200,  203,  217,  227,  204,  220,  229,

      231,  230,  243,  244, 1528, 1528,    0,  209,  222,  225,
      230,  233,  236,  239, 1528,  263,    0,    0,  263,  713,
      290,  296,  298,  325,    0,  250,  261,  666,  264,  247,
      273,  266,  282,  651,  299,  302,  305,  308,  311,  314,
      317,  682,  683,  680, 1528,  323,  339,  363,  364,  365,
      366,  367,  368,  369,  246,  685,  373,  374,  376,  375,
      370,  680,  334,  337,  340,  408,  419,  421,  448,    0,
      419,  343,  634,  369,  276,  377,  347,  380,  635,  383,
      386,  389,  396,  405,  430,  433,  436,  439,  442,  671,
        0,    0,  462,  442,  488,  489,  492,  491,  493,  673,

      671,  494,  495,  500,  496,  501,  497,  498,    0,  671,
      507,  518,  536,  563,    0,  466,  494,  497,  500,  503,
      506,  511,  520,  537,  540,    0,    0,  516,  668,  507,
      530,  577,  667,  558,  561,  586,  587,  588,  666,  591,
      512,  657,  594,  604,  606,  633,    0,  561,  564,  572,
        0,  597,  599,  653,  619,  610,  613,  595,  633,  499,
      625,  628,  447,  658,  666,  693,    0,    0,  443,  626,
      627,  436,  410,  635,  371,  314,  668,  679,  720,    0,
      634,  257,  202,  691,  718,  747,    0,   99,  745,  772,
      799,    0,  774,  776,  826,    0,  784,  797,  853,    0,

      824,  851,  880,    0,  878,  905,  932,    0,  907,  909,
      959,    0,  917,  930,  986,    0,  957,  984, 1013,    0,
     1011, 1038, 1065,    0, 1040, 1042, 1092,    0, 1050, 1063,
     1119,    0, 1090, 1117, 1146,    0, 1144, 1171, 1198,    0,
        0,    0, 1225,    0, 1528, 1243, 1528, 1274, 1286, 1294,
     1305, 1313, 1320, 1331, 1343, 1355, 1364, 1367, 1376, 1382,
     1391, 1398, 1405, 1412, 1419, 1426, 1433, 1440, 1447, 1454,
     1461, 1468, 1475, 1482, 1489, 1496, 1503, 1510, 1517,   78
    } ;

static const flex_int16_t yy_def[381] =
    {   0,
      347,    1,  348,  348,  347,  347,  347,  347,  347,  349,
      350,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      351,  347,  347,   23,   23,   23,   23,  352,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  354,  347,  350,  355,  355,   23,   23,  356,  347,
      347,  349,  347,  349,  350,  347,  347,  347,  351,  347,
      357,   23,   72,  358,   72,  347,  347,  347,  347,  347,
      347,  347,  347,   72,   72,   72,  352,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,

      353,  353,  353,  353,  347,  347,   75,  347,  347,  347,
      347,  347,  347,  347,  347,  354,  355,  356,  347,  347,
      347,  359,  359,   75,  124,  360,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  124,  124,  124,  347,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  347,  347,  347,  347,  361,  361,  124,  169,
      360,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  169,
      169,  169,  353,  353,  353,  353,  353,  353,  353,  353,

      353,  353,  353,  353,  353,  353,  353,  353,   75,  347,
      347,  362,  362,   75,  214,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,   75,  214,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  347,  363,  363,  214,  246,  347,  347,  347,
      171,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  347,  364,  364,  246,  266,  171,  353,  353,
      353,  353,  353,  353,  353,  347,  365,  365,  266,  279,
      353,  353,  353,  366,  366,  279,  286,  353,  367,  367,
      286,  291,  368,  368,  291,  295,  369,  369,  295,  299,

      370,  370,  299,  303,  371,  371,  303,  307,  372,  372,
      307,  311,  373,  373,  311,  315,  374,  374,  315,  319,
      375,  375,  319,  323,  376,  376,  323,  327,  377,  377,
      327,  331,  378,  378,  331,  335,  379,  379,  335,  339,
      380,  380,  339,  343,  347,  343,    0,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347
    } ;

static const flex_int16_t yy_nxt[1600] =
    {   0,
        6,    7,    8,    7,    9,   10,   11,    6,   12,   13,
       14,   15,   16,   17,    6,   18,   19,   20,   21,   22,
       23,   23,   24,   23,   25,   23,   26,   24,   24,   27,
       24,    6,   28,    6,   29,   30,   31,   32,   33,   29,
       29,   29,   34,   29,   29,   35,   36,   37,   38,   29,
       29,   39,   29,   29,   29,   29,   40,   41,   42,   43,
        6,    6,    6,   44,   45,   46,   47,   48,   49,   50,
       51,   52,  145,   61,   53,   61,   54,   60,   60,   60,
       55,   60,   60,   60,   63,  345,   66,   56,   67,  116,
       68,   61,   57,   90,   98,  145,   91,   57,   57,   58,

       57,  147,   92,   99,  110,  110,  100,  112,  112,  101,
       64,   71,  102,  107,  107,  107,  145,   72,   71,   66,
       73,   74,  148,  119,   73,   73,   73,   73,   73,   73,
       73,   73,   73,   73,   73,  137,  137,   71,   75,   75,
       75,   75,   75,   75,   75,   75,   75,   75,   75,   75,
       75,   75,   75,   75,   75,   75,   75,   75,   75,   75,
      109,  109,  109,  111,  111,  111,   63,   76,   77,   78,
       79,   80,   81,   82,   83,  113,  113,  113,   61,   66,
       61,   67,  122,  121,   75,   75,   75,  145,  122,  122,
      139,  139,   64,  127,  128,  129,  130,  131,  132,  133,

      134,  136,  136,  136,  138,  138,  138,  145,  122,  122,
      140,  140,  140,  146,  145,  124,  122,  145,  125,  145,
      145,  145,  125,  125,  125,  125,  125,  125,  125,  125,
      125,  125,  125,  150,  145,  122,  347,  145,  151,  152,
      149,  156,   75,  347,  145,   75,  145,  145,  145,   75,
       75,   75,   75,   75,   75,   75,   75,   75,   75,   75,
      145,  145,  347,  145,  116,  154,   61,   74,  153,  107,
      107,  107,  157,  159,  145,   66,  158,   67,  155,  119,
      160,  161,  107,  107,  107,  107,  107,  107,  202,  162,
      107,  107,  107,  163,  163,  163,  164,  164,  164,  165,

      165,  165,   66,  167,   67,  167,  166,  182,  182,  167,
      167,  167,  167,  172,  173,  174,  175,  176,  177,  178,
      179,  126,  126,  126,  181,  181,  181,  184,  184,  167,
      276,  167,  167,  183,  183,  183,  218,  218,  169,  167,
      145,  170,  185,  185,  185,  170,  170,  170,  170,  170,
      170,  170,  170,  170,  170,  170,  145,  193,  167,   75,
       75,   75,   75,   75,   75,   75,   75,   75,   75,   75,
       75,  187,  187,  187,  188,  188,  188,  189,  189,  189,
      145,  145,  145,  145,  145,  145,  145,  145,  145,  194,
      145,  145,  145,  145,  209,  209,  209,  209,  209,  209,

      209,  209,  209,  171,  171,  171,  200,  195,  220,  220,
      199,  198,  206,  203,  201,  196,  207,  197,  204,  208,
       66,  210,   67,  210,  211,  205,  212,  145,  212,  217,
      217,  217,  212,  212,  212,  212,   74,  219,  219,  219,
      221,  221,  221,  126,  126,  126,  126,  126,  126,  126,
      126,  126,  212,  145,  212,  212,  126,  126,  126,  145,
      145,  214,  212,  276,  215,  223,  223,  223,  215,  215,
      215,  215,  215,  215,  215,  215,  215,  215,  215,  145,
      229,  212,  172,  173,  174,  175,  176,  177,  178,  179,
      224,  224,  224,  225,  225,  225,  226,  226,  226,  226,

      226,  226,  226,  226,  226,  145,  145,  228,  145,  145,
      145,  145,  145,  145,  145,  145,  145,  145,  145,   66,
      210,   67,  210,  211,  145,  244,  171,  171,  171,  145,
      238,  244,  244,  145,  230,  231,  232,  236,  237,  239,
      235,  240,  233,  244,  253,  234,  262,  145,  241,  244,
      244,  244,  252,  242,  171,  171,  171,  171,  171,  171,
      171,  171,  171,  248,  248,  248,  249,  249,  249,  244,
      244,  250,  250,  250,  254,  145,  246,  244,  145,  247,
      251,  251,  251,  247,  247,  247,  247,  247,  247,  247,
      247,  247,  247,  247,  145,  256,  244,  251,  251,  251,

      251,  251,  251,  145,  145,  145,  257,  263,  145,  263,
      243,  264,  145,  264,  145,  255,  145,  264,  264,  264,
      264,  268,  268,  268,  268,  268,  268,  145,  260,  261,
      145,  258,  268,  268,  268,  269,  145,  264,  259,  264,
      264,  270,  145,  145,  145,  145,  266,  264,  272,  267,
      145,  145,  145,  267,  267,  267,  267,  267,  267,  267,
      267,  267,  267,  267,  271,  277,  264,  273,  275,  283,
      145,  277,  277,  277,  145,  284,  274,  281,  282,  277,
      277,  284,  284,  145,  145,  145,  284,  243,  145,  288,
      145,  277,  284,  284,  227,  222,  216,  145,  289,  277,

      277,  284,  145,  192,  289,  289,  279,  277,  191,  280,
      190,  186,  284,  280,  280,  280,  280,  280,  280,  280,
      280,  280,  280,  280,  289,  289,  277,  284,  180,  120,
      145,  289,  289,  286,  284,  144,  287,  143,  142,  141,
      287,  287,  287,  287,  287,  287,  287,  287,  287,  287,
      287,  289,  293,  284,  289,  135,  120,  347,  293,  293,
      291,  289,   86,  292,  114,  108,  106,  292,  292,  292,
      292,  292,  292,  292,  292,  292,  292,  292,  293,  293,
      289,  297,  105,  297,  104,  293,  293,  297,  297,  297,
      297,  301,  103,   97,   96,   95,   94,  301,  301,   93,

       89,   86,   85,   84,  301,  293,  293,  297,   70,  297,
      301,  301,  295,  293,  347,  296,  347,  301,  347,  296,
      296,  296,  296,  296,  296,  296,  296,  296,  296,  296,
      301,  305,  293,  297,  347,  347,  347,  305,  305,  299,
      297,  347,  300,  347,  347,  347,  300,  300,  300,  300,
      300,  300,  300,  300,  300,  300,  300,  305,  305,  297,
      301,  347,  347,  347,  305,  305,  303,  301,  347,  304,
      347,  347,  347,  304,  304,  304,  304,  304,  304,  304,
      304,  304,  304,  304,  305,  309,  301,  305,  347,  347,
      347,  309,  309,  307,  305,  347,  308,  347,  347,  347,

      308,  308,  308,  308,  308,  308,  308,  308,  308,  308,
      308,  309,  309,  305,  313,  347,  313,  347,  309,  309,
      313,  313,  313,  313,  317,  347,  347,  347,  347,  347,
      317,  317,  347,  347,  347,  347,  347,  317,  309,  309,
      313,  347,  313,  317,  317,  311,  309,  347,  312,  347,
      317,  347,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  317,  321,  309,  313,  347,  347,  347,
      321,  321,  315,  313,  347,  316,  347,  347,  347,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      321,  321,  313,  317,  347,  347,  347,  321,  321,  319,

      317,  347,  320,  347,  347,  347,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  321,  325,  317,
      321,  347,  347,  347,  325,  325,  323,  321,  347,  324,
      347,  347,  347,  324,  324,  324,  324,  324,  324,  324,
      324,  324,  324,  324,  325,  325,  321,  329,  347,  329,
      347,  325,  325,  329,  329,  329,  329,  333,  347,  347,
      347,  347,  347,  333,  333,  347,  347,  347,  347,  347,
      333,  325,  325,  329,  347,  329,  333,  333,  327,  325,
      347,  328,  347,  333,  347,  328,  328,  328,  328,  328,
      328,  328,  328,  328,  328,  328,  333,  337,  325,  329,

      347,  347,  347,  337,  337,  331,  329,  347,  332,  347,
      347,  347,  332,  332,  332,  332,  332,  332,  332,  332,
      332,  332,  332,  337,  337,  329,  333,  347,  347,  347,
      337,  337,  335,  333,  347,  336,  347,  347,  347,  336,
      336,  336,  336,  336,  336,  336,  336,  336,  336,  336,
      337,  341,  333,  337,  347,  347,  347,  341,  341,  339,
      337,  347,  340,  347,  347,  347,  340,  340,  340,  340,
      340,  340,  340,  340,  340,  340,  340,  341,  341,  337,
      347,  347,  347,  347,  341,  341,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,

      347,  347,  347,  347,  341,  341,  347,  347,  347,  347,
      347,  343,  341,  347,  344,  347,  347,  347,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  347,
      347,  341,  347,  347,  347,  347,  347,  347,   75,  347,
      347,  346,  347,  347,  347,  346,  346,  346,  346,  346,
      346,  346,  346,  346,  346,  346,  347,  347,  347,   75,
      347,  347,  347,   75,   75,   75,   75,   75,   75,   75,
       75,   75,   75,   75,   59,   59,   59,   59,   59,   59,
       59,   59,   59,   59,   59,   59,   62,   62,   62,   62,
       62,   62,   62,   62,   62,   62,   62,   62,   65,   65,

       65,   65,  347,   65,   65,   69,   69,  347,   69,   69,
       69,   69,   69,   69,   69,   69,   69,   87,   87,   87,
       87,  347,   87,   87,   88,  347,  347,   88,  347,   88,
       88,  115,  115,  347,  115,  115,  115,  115,  115,  115,
      115,  115,  115,  117,  117,  347,  117,  117,  117,  117,
      117,  117,  117,  117,  117,  118,  347,  347,  118,  118,
      118,  118,  118,  118,  118,  118,  118,  123,  123,  123,
      347,  123,  347,  123,  126,  347,  347,  347,  126,  168,
      168,  168,  347,  168,  347,  168,  171,  347,  347,  171,
      171,  347,  171,  171,  213,  213,  213,  347,  213,  347,

      213,  245,  245,  245,  347,  245,  347,  245,  265,  265,
      265,  347,  265,  347,  265,  278,  278,  278,  347,  278,
      347,  278,  285,  285,  285,  347,  285,  347,  285,  290,
      290,  290,  347,  290,  347,  290,  294,  294,  294,  347,
      294,  347,  294,  298,  298,  298,  347,  298,  347,  298,
      302,  302,  302,  347,  302,  347,  302,  306,  306,  306,
      347,  306,  347,  306,  310,  310,  310,  347,  310,  347,
      310,  314,  314,  314,  347,  314,  347,  314,  318,  318,
      318,  347,  318,  347,  318,  322,  322,  322,  347,  322,
      347,  322,  326,  326,  326,  347,  326,  347,  326,  330,

      330,  330,  347,  330,  347,  330,  334,  334,  334,  347,
      334,  347,  334,  338,  338,  338,  347,  338,  347,  338,
      342,  342,  342,  347,  342,  347,  342,    5,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347

    } ;

static const flex_int16_t yy_chk[1600] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,   90,    7,    2,    7,    2,    3,    3,    3,
        2,    4,    4,    4,   10,  380,   19,    2,   19,   52,
       19,   52,    2,   31,   37,   91,   31,    2,    2,    2,

        2,   90,   31,   37,   47,   47,   37,   49,   49,   37,
       10,   23,   37,   44,   44,   44,  288,   23,   23,   66,
       23,   23,   91,   66,   23,   23,   23,   23,   23,   23,
       23,   23,   23,   23,   23,   79,   79,   23,   23,   23,
       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,
       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,
       46,   46,   46,   48,   48,   48,   62,   23,   23,   23,
       23,   23,   23,   23,   23,   50,   50,   50,   61,   68,
       61,   68,   71,   68,   76,   76,   76,   89,   71,   71,
       81,   81,   62,   74,   74,   74,   74,   74,   74,   74,

       74,   78,   78,   78,   80,   80,   80,   92,   71,   72,
       82,   82,   82,   89,   93,   72,   72,   94,   72,  283,
       95,   98,   72,   72,   72,   72,   72,   72,   72,   72,
       72,   72,   72,   93,   96,   72,   75,   99,   94,   95,
       92,   98,   75,   75,   97,   75,  100,  102,  101,   75,
       75,   75,   75,   75,   75,   75,   75,   75,   75,   75,
      103,  104,   75,  155,  116,   97,  116,  126,   96,  108,
      108,  108,   99,  101,  282,  119,  100,  119,   97,  119,
      102,  103,  109,  109,  109,  110,  110,  110,  155,  104,
      111,  111,  111,  112,  112,  112,  113,  113,  113,  114,

      114,  114,  121,  122,  121,  123,  121,  130,  130,  122,
      122,  123,  123,  126,  126,  126,  126,  126,  126,  126,
      126,  127,  127,  127,  129,  129,  129,  132,  132,  122,
      276,  123,  124,  131,  131,  131,  175,  175,  124,  124,
      146,  124,  133,  133,  133,  124,  124,  124,  124,  124,
      124,  124,  124,  124,  124,  124,  147,  146,  124,  135,
      135,  135,  136,  136,  136,  137,  137,  137,  138,  138,
      138,  139,  139,  139,  140,  140,  140,  141,  141,  141,
      148,  149,  150,  151,  152,  153,  154,  161,  275,  147,
      157,  158,  160,  159,  163,  163,  163,  164,  164,  164,

      165,  165,  165,  172,  172,  172,  153,  148,  177,  177,
      152,  151,  159,  157,  154,  149,  160,  150,  158,  161,
      166,  166,  166,  166,  166,  158,  167,  273,  168,  174,
      174,  174,  167,  167,  168,  168,  171,  176,  176,  176,
      178,  178,  178,  180,  180,  180,  181,  181,  181,  182,
      182,  182,  167,  272,  168,  169,  183,  183,  183,  194,
      269,  169,  169,  263,  169,  184,  184,  184,  169,  169,
      169,  169,  169,  169,  169,  169,  169,  169,  169,  193,
      194,  169,  171,  171,  171,  171,  171,  171,  171,  171,
      185,  185,  185,  186,  186,  186,  187,  187,  187,  188,

      188,  188,  189,  189,  189,  195,  196,  193,  198,  197,
      199,  202,  203,  205,  207,  208,  260,  204,  206,  211,
      211,  211,  211,  211,  230,  212,  216,  216,  216,  241,
      205,  212,  212,  228,  195,  196,  197,  203,  204,  206,
      202,  207,  198,  213,  230,  199,  241,  231,  207,  213,
      213,  212,  228,  208,  217,  217,  217,  218,  218,  218,
      219,  219,  219,  220,  220,  220,  221,  221,  221,  213,
      214,  222,  222,  222,  231,  234,  214,  214,  235,  214,
      223,  223,  223,  214,  214,  214,  214,  214,  214,  214,
      214,  214,  214,  214,  232,  234,  214,  224,  224,  224,

      225,  225,  225,  236,  237,  238,  235,  243,  240,  243,
      243,  244,  258,  245,  252,  232,  253,  244,  244,  245,
      245,  248,  248,  248,  249,  249,  249,  256,  238,  240,
      257,  236,  250,  250,  250,  252,  255,  244,  237,  245,
      246,  253,  261,  270,  271,  262,  246,  246,  256,  246,
      259,  281,  274,  246,  246,  246,  246,  246,  246,  246,
      246,  246,  246,  246,  255,  264,  246,  259,  262,  274,
      254,  264,  264,  265,  242,  277,  261,  270,  271,  265,
      265,  277,  277,  239,  233,  229,  278,  210,  201,  281,
      200,  264,  278,  278,  190,  179,  173,  162,  284,  265,

      266,  277,  156,  144,  284,  284,  266,  266,  143,  266,
      142,  134,  278,  266,  266,  266,  266,  266,  266,  266,
      266,  266,  266,  266,  284,  285,  266,  279,  128,  120,
       88,  285,  285,  279,  279,   86,  279,   85,   84,   83,
      279,  279,  279,  279,  279,  279,  279,  279,  279,  279,
      279,  285,  289,  279,  286,   77,   67,   64,  289,  289,
      286,  286,   58,  286,   51,   45,   42,  286,  286,  286,
      286,  286,  286,  286,  286,  286,  286,  286,  289,  290,
      286,  293,   40,  294,   39,  290,  290,  293,  293,  294,
      294,  297,   38,   36,   35,   34,   33,  297,  297,   32,

       30,   27,   26,   25,  298,  290,  291,  293,   22,  294,
      298,  298,  291,  291,    5,  291,    0,  297,    0,  291,
      291,  291,  291,  291,  291,  291,  291,  291,  291,  291,
      298,  301,  291,  295,    0,    0,    0,  301,  301,  295,
      295,    0,  295,    0,    0,    0,  295,  295,  295,  295,
      295,  295,  295,  295,  295,  295,  295,  301,  302,  295,
      299,    0,    0,    0,  302,  302,  299,  299,    0,  299,
        0,    0,    0,  299,  299,  299,  299,  299,  299,  299,
      299,  299,  299,  299,  302,  305,  299,  303,    0,    0,
        0,  305,  305,  303,  303,    0,  303,    0,    0,    0,

      303,  303,  303,  303,  303,  303,  303,  303,  303,  303,
      303,  305,  306,  303,  309,    0,  310,    0,  306,  306,
      309,  309,  310,  310,  313,    0,    0,    0,    0,    0,
      313,  313,    0,    0,    0,    0,    0,  314,  306,  307,
      309,    0,  310,  314,  314,  307,  307,    0,  307,    0,
      313,    0,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  314,  317,  307,  311,    0,    0,    0,
      317,  317,  311,  311,    0,  311,    0,    0,    0,  311,
      311,  311,  311,  311,  311,  311,  311,  311,  311,  311,
      317,  318,  311,  315,    0,    0,    0,  318,  318,  315,

      315,    0,  315,    0,    0,    0,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  318,  321,  315,
      319,    0,    0,    0,  321,  321,  319,  319,    0,  319,
        0,    0,    0,  319,  319,  319,  319,  319,  319,  319,
      319,  319,  319,  319,  321,  322,  319,  325,    0,  326,
        0,  322,  322,  325,  325,  326,  326,  329,    0,    0,
        0,    0,    0,  329,  329,    0,    0,    0,    0,    0,
      330,  322,  323,  325,    0,  326,  330,  330,  323,  323,
        0,  323,    0,  329,    0,  323,  323,  323,  323,  323,
      323,  323,  323,  323,  323,  323,  330,  333,  323,  327,

        0,    0,    0,  333,  333,  327,  327,    0,  327,    0,
        0,    0,  327,  327,  327,  327,  327,  327,  327,  327,
      327,  327,  327,  333,  334,  327,  331,    0,    0,    0,
      334,  334,  331,  331,    0,  331,    0,    0,    0,  331,
      331,  331,  331,  331,  331,  331,  331,  331,  331,  331,
      334,  337,  331,  335,    0,    0,    0,  337,  337,  335,
      335,    0,  335,    0,    0,    0,  335,  335,  335,  335,
      335,  335,  335,  335,  335,  335,  335,  337,  338,  335,
        0,    0,    0,    0,  338,  338,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,  338,  339,    0,    0,    0,    0,
        0,  339,  339,    0,  339,    0,    0,    0,  339,  339,
      339,  339,  339,  339,  339,  339,  339,  339,  339,    0,
        0,  339,  343,    0,    0,    0,    0,    0,  343,  343,
        0,  343,    0,    0,    0,  343,  343,  343,  343,  343,
      343,  343,  343,  343,  343,  343,    0,    0,  343,  346,
        0,    0,    0,  346,  346,  346,  346,  346,  346,  346,
      346,  346,  346,  346,  348,  348,  348,  348,  348,  348,
      348,  348,  348,  348,  348,  348,  349,  349,  349,  349,
      349,  349,  349,  349,  349,  349,  349,  349,  350,  350,

      350,  350,    0,  350,  350,  351,  351,    0,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  352,  352,  352,
      352,    0,  352,  352,  353,    0,    0,  353,    0,  353,
      353,  354,  354,    0,  354,  354,  354,  354,  354,  354,
      354,  354,  354,  355,  355,    0,  355,  355,  355,  355,
      355,  355,  355,  355,  355,  356,    0,    0,  356,  356,
      356,  356,  356,  356,  356,  356,  356,  357,  357,  357,
        0,  357,    0,  357,  358,    0,    0,    0,  358,  359,
      359,  359,    0,  359,    0,  359,  360,    0,    0,  360,
      360,    0,  360,  360,  361,  361,  361,    0,  361,    0,

      361,  362,  362,  362,    0,  362,    0,  362,  363,  363,
      363,    0,  363,    0,  363,  364,  364,  364,    0,  364,
        0,  364,  365,  365,  365,    0,  365,    0,  365,  366,
      366,  366,    0,  366,    0,  366,  367,  367,  367,    0,
      367,    0,  367,  368,  368,  368,    0,  368,    0,  368,
      369,  369,  369,    0,  369,    0,  369,  370,  370,  370,
        0,  370,    0,  370,  371,  371,  371,    0,  371,    0,
      371,  372,  372,  372,    0,  372,    0,  372,  373,  373,
      373,    0,  373,    0,  373,  374,  374,  374,    0,  374,
        0,  374,  375,  375,  375,    0,  375,    0,  375,  376,

      376,  376,    0,  376,    0,  376,  377,  377,  377,    0,
      377,    0,  377,  378,  378,  378,    0,  378,    0,  378,
      379,  379,  379,    0,  379,    0,  379,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347

    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[58] =
    {   0,
1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,     };

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#line 1 "beancount/parser/lexer.l"
/* -*- mode: c -*- */
/* A flex lexer for Beancount. */
/* Options */
/* %option nodefault */
/* %option debug */
/* %option stack */
/* %option 8bit */
/* Top Code. This is included in the FLex generated header file. */

/* Definitions. */
#line 57 "beancount/parser/lexer.l"

#include <math.h>
#include <stdlib.h>
#include <stdarg.h>

#include "grammar.h"
#include "tokens.h"

struct _yyextra_t {
    /* The filename being tokenized. */
    PyObject* filename;

    /* The encoding to use for converting strings. */
    const char* encoding;
};

#define yy_filename yyget_extra(yyscanner)->filename
#define yy_encoding yyget_extra(yyscanner)->encoding

/* Build and accumulate an error on the builder object. */
void build_lexer_error(YYLTYPE* loc, PyObject* builder, const char* format, ...);

/* Build and accumulate an error on the builder object using the current
 * exception state. */
void build_lexer_error_from_exception(YYLTYPE* loc, PyObject* builder);

int pyfile_read_into(PyObject *file, char *buf, size_t max_size);

#define YY_INPUT(buf, result, max_size)                         \
    result = pyfile_read_into((PyObject *)yyin, buf, max_size);

#define YY_USER_ACTION                                                  \
    {                                                                   \
        yylloc->first_line = yylineno;                                  \
        yylloc->last_line = yylloc->first_line;                         \
        yylloc->first_column = yycolumn;                                \
        yylloc->last_column = yycolumn + yyleng - 1;                    \
        yylloc->file_name = yy_filename;                                \
        yycolumn += yyleng;                                             \
    }

/* Skip the rest of the input line.  This needs to be implemented as a
 * macro because input() and unput() are themselves macros tha use
 * variable definitions internal to the yylex() function. */
#define yy_skip_line()                          \
    do {                                        \
        for (;;) {                              \
            int c = input(yyscanner);           \
            if (c == 0 || c == -1) {		\
                break;                          \
            }                                   \
            if (c == '\n') {                    \
                unput(c);                       \
                break;                          \
            }                                   \
        }                                       \
    } while (0)

#line 1046 "beancount/parser/lexer.c"
/* A start condition for chomping an invalid token. */

#line 1049 "beancount/parser/lexer.c"

#define INITIAL 0
#define INVALID 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#define YY_EXTRA_TYPE yyextra_t*

/* Holds the entire state of the reentrant scanner. */
struct yyguts_t
    {

    /* User-defined. Not touched by flex. */
    YY_EXTRA_TYPE yyextra_r;

    /* The rest are the same as the globals declared in the non-reentrant scanner. */
    FILE *yyin_r, *yyout_r;
    size_t yy_buffer_stack_top; /**< index of top of stack. */
    size_t yy_buffer_stack_max; /**< capacity of stack. */
    YY_BUFFER_STATE * yy_buffer_stack; /**< Stack as an array. */
    char yy_hold_char;
    int yy_n_chars;
    int yyleng_r;
    char *yy_c_buf_p;
    int yy_init;
    int yy_start;
    int yy_did_buffer_switch_on_eof;
    int yy_start_stack_ptr;
    int yy_start_stack_depth;
    int *yy_start_stack;
    yy_state_type yy_last_accepting_state;
    char* yy_last_accepting_cpos;

    int yylineno_r;
    int yy_flex_debug_r;

    char *yytext_r;
    int yy_more_flag;
    int yy_more_len;

    YYSTYPE * yylval_r;

    YYLTYPE * yylloc_r;

    }; /* end struct yyguts_t */

static int yy_init_globals ( yyscan_t yyscanner );

    /* This must go here because YYSTYPE and YYLTYPE are included
     * from bison output in section 1.*/
    #    define yylval yyg->yylval_r
    
    #    define yylloc yyg->yylloc_r
    
int yylex_init (yyscan_t* scanner);

int yylex_init_extra ( YY_EXTRA_TYPE user_defined, yyscan_t* scanner);

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( yyscan_t yyscanner );

int yyget_debug ( yyscan_t yyscanner );

void yyset_debug ( int debug_flag , yyscan_t yyscanner );

YY_EXTRA_TYPE yyget_extra ( yyscan_t yyscanner );

void yyset_extra ( YY_EXTRA_TYPE user_defined , yyscan_t yyscanner );

FILE *yyget_in ( yyscan_t yyscanner );

void yyset_in  ( FILE * _in_str , yyscan_t yyscanner );

FILE *yyget_out ( yyscan_t yyscanner );

void yyset_out  ( FILE * _out_str , yyscan_t yyscanner );

			int yyget_leng ( yyscan_t yyscanner );

char *yyget_text ( yyscan_t yyscanner );

int yyget_lineno ( yyscan_t yyscanner );

void yyset_lineno ( int _line_number , yyscan_t yyscanner );

int yyget_column  ( yyscan_t yyscanner );

void yyset_column ( int _column_no , yyscan_t yyscanner );

YYSTYPE * yyget_lval ( yyscan_t yyscanner );

void yyset_lval ( YYSTYPE * yylval_param , yyscan_t yyscanner );

       YYLTYPE *yyget_lloc ( yyscan_t yyscanner );
    
        void yyset_lloc ( YYLTYPE * yylloc_param , yyscan_t yyscanner );
    
/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( yyscan_t yyscanner );
#else
extern int yywrap ( yyscan_t yyscanner );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  , yyscan_t yyscanner);
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int , yyscan_t yyscanner);
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * , yyscan_t yyscanner);
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( yyscan_t yyscanner );
#else
static int input ( yyscan_t yyscanner );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg , yyscanner)
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex \
               (YYSTYPE * yylval_param, YYLTYPE * yylloc_param , yyscan_t yyscanner);

#define YY_DECL int yylex \
               (YYSTYPE * yylval_param, YYLTYPE * yylloc_param , yyscan_t yyscanner)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    yylval = yylval_param;

    yylloc = yylloc_param;

	if ( !yyg->yy_init )
		{
		yyg->yy_init = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yyg->yy_start )
			yyg->yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack (yyscanner);
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner);
		}

		yy_load_buffer_state( yyscanner );
		}

	{
#line 134 "beancount/parser/lexer.l"


#line 137 "beancount/parser/lexer.l"
 /* Newlines are output as explicit tokens, because lines matter in the syntax. */
#line 1340 "beancount/parser/lexer.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yyg->yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yyg->yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yyg->yy_start;
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				yyg->yy_last_accepting_state = yy_current_state;
				yyg->yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 348 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 347 );
		yy_cp = yyg->yy_last_accepting_cpos;
		yy_current_state = yyg->yy_last_accepting_state;

yy_find_action:
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    do{ yylineno++;
        yycolumn=0;
    }while(0)
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yyg->yy_hold_char;
			yy_cp = yyg->yy_last_accepting_cpos;
			yy_current_state = yyg->yy_last_accepting_state;
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 138 "beancount/parser/lexer.l"
{
    yycolumn = 1;
    return EOL;
}
	YY_BREAK
/* Ignore whitespace, except when found at the beginning of a line
    and followed by a regular character. This is how we detect an
    initial indent and thus group postings and comments together in
    the grammar. */
case 2:
*yy_cp = yyg->yy_hold_char; /* undo effects of setting up yytext */
yyg->yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 147 "beancount/parser/lexer.l"
{ return INDENT; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 148 "beancount/parser/lexer.l"
{ }
	YY_BREAK
/* Special handling for characters beginning a line to be ignored. */
case 4:
YY_RULE_SETUP
#line 151 "beancount/parser/lexer.l"
{ }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 152 "beancount/parser/lexer.l"
{ yy_skip_line(); }
	YY_BREAK
/* Comments. */
case 6:
YY_RULE_SETUP
#line 155 "beancount/parser/lexer.l"
{ }
	YY_BREAK
/* Characters with special meanings have their own tokens. */
case 7:
YY_RULE_SETUP
#line 158 "beancount/parser/lexer.l"
{ return PIPE; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 159 "beancount/parser/lexer.l"
{ return ATAT; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 160 "beancount/parser/lexer.l"
{ return AT; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 161 "beancount/parser/lexer.l"
{ return LCURLCURL; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 162 "beancount/parser/lexer.l"
{ return RCURLCURL; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 163 "beancount/parser/lexer.l"
{ return LCURL; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 164 "beancount/parser/lexer.l"
{ return RCURL; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 165 "beancount/parser/lexer.l"
{ return COMMA; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 166 "beancount/parser/lexer.l"
{ return TILDE; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 167 "beancount/parser/lexer.l"
{ return PLUS; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 168 "beancount/parser/lexer.l"
{ return MINUS; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 169 "beancount/parser/lexer.l"
{ return SLASH; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 170 "beancount/parser/lexer.l"
{ return LPAREN; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 171 "beancount/parser/lexer.l"
{ return RPAREN; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 172 "beancount/parser/lexer.l"
{ return HASH; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 173 "beancount/parser/lexer.l"
{ return ASTERISK; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 174 "beancount/parser/lexer.l"
{ return COLON; }
	YY_BREAK
/* Characters that may be used as flags in-lieu of a 'txn' keyword in a
    transaction declaration.  Note: Make sure to include all the values from
    beancount.core.flags in order for round-trips between text and entries to
    be possible. {5307d8fa1e7b} */
case 24:
YY_RULE_SETUP
#line 180 "beancount/parser/lexer.l"
{
    yylval->character = yytext[0];
    return FLAG;
}
	YY_BREAK
/* Keywords. */
case 25:
YY_RULE_SETUP
#line 186 "beancount/parser/lexer.l"
{ return TXN; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 187 "beancount/parser/lexer.l"
{ return BALANCE; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 188 "beancount/parser/lexer.l"
{ return OPEN; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 189 "beancount/parser/lexer.l"
{ return CLOSE; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 190 "beancount/parser/lexer.l"
{ return COMMODITY; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 191 "beancount/parser/lexer.l"
{ return PAD; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 192 "beancount/parser/lexer.l"
{ return EVENT; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 193 "beancount/parser/lexer.l"
{ return QUERY; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 194 "beancount/parser/lexer.l"
{ return CUSTOM; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 195 "beancount/parser/lexer.l"
{ return PRICE; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 196 "beancount/parser/lexer.l"
{ return NOTE; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 197 "beancount/parser/lexer.l"
{ return DOCUMENT; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 198 "beancount/parser/lexer.l"
{ return PUSHTAG; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 199 "beancount/parser/lexer.l"
{ return POPTAG; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 200 "beancount/parser/lexer.l"
{ return PUSHMETA; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 201 "beancount/parser/lexer.l"
{ return POPMETA; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 202 "beancount/parser/lexer.l"
{ return OPTION; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 203 "beancount/parser/lexer.l"
{ return PLUGIN; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 204 "beancount/parser/lexer.l"
{ return INCLUDE; }
	YY_BREAK
/* Boolean values. */
case 44:
YY_RULE_SETUP
#line 207 "beancount/parser/lexer.l"
{
    return token(BOOL, true);
}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 211 "beancount/parser/lexer.l"
{
    return token(BOOL, false);
}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 215 "beancount/parser/lexer.l"
{
    return token(NONE);
}
	YY_BREAK
/* Dates. */
case 47:
YY_RULE_SETUP
#line 220 "beancount/parser/lexer.l"
{
    return token(DATE, yytext);
}
	YY_BREAK
/* Account names. */
case 48:
YY_RULE_SETUP
#line 225 "beancount/parser/lexer.l"
{
    return token(ACCOUNT, yytext);
}
	YY_BREAK
/* Currencies. These are defined as uppercase only in order to disambiguate the
  * syntax. This is kept in sync with beancount.core.amount.CURRENCY_RE. */
case 49:
YY_RULE_SETUP
#line 231 "beancount/parser/lexer.l"
{
    return token(CURRENCY, yytext, yyleng);
}
	YY_BREAK
/* String literals. */
case 50:
/* rule 50 can match eol */
YY_RULE_SETUP
#line 236 "beancount/parser/lexer.l"
{
    return token(STRING, yytext + 1, yyleng - 2, yy_encoding);
}
	YY_BREAK
/* Numbers */
case 51:
YY_RULE_SETUP
#line 241 "beancount/parser/lexer.l"
{
    return token(NUMBER, yytext);
}
	YY_BREAK
/* Tags */
case 52:
YY_RULE_SETUP
#line 246 "beancount/parser/lexer.l"
{
    return token(TAG, yytext + 1, yyleng - 1);
}
	YY_BREAK
/* Links */
case 53:
YY_RULE_SETUP
#line 251 "beancount/parser/lexer.l"
{
    return token(LINK, yytext + 1, yyleng - 1);
}
	YY_BREAK
/* Keys */
case 54:
*yy_cp = yyg->yy_hold_char; /* undo effects of setting up yytext */
yyg->yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 256 "beancount/parser/lexer.l"
{
    return token(KEY, yytext, yyleng);
}
	YY_BREAK
/* Default rule. {bf253a29a820} */
case 55:
YY_RULE_SETUP
#line 261 "beancount/parser/lexer.l"
{
    unput(*yytext);
    BEGIN(INVALID);
}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(INVALID):
#line 266 "beancount/parser/lexer.l"
{
    /* Ensure location data is populated. */
    YY_USER_ACTION;
    return YYEOF;
}
	YY_BREAK
/* Note: We use a subparser here because if we set a default rule to chomp this
    pattern, it would take precedence over valid rules if the matched text is
    longer and thus would break the lexer. Writing our own lexer would fix
    this and more. {bba169a1d35a} */
case 56:
YY_RULE_SETUP
#line 276 "beancount/parser/lexer.l"
{
    PyObject* input = PyUnicode_Decode(yytext, yyleng, "utf-8", "backslashreplace");
    build_lexer_error(yylloc, builder, "Invalid token: '%U'", input);
    BEGIN(INITIAL);
    return YYerror;
}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 284 "beancount/parser/lexer.l"
ECHO;
	YY_BREAK
#line 1771 "beancount/parser/lexer.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yyg->yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yyg->yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yyg->yy_c_buf_p <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yyg->yy_c_buf_p = yyg->yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state( yyscanner );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state , yyscanner);

			yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yyg->yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yyg->yy_last_accepting_cpos;
				yy_current_state = yyg->yy_last_accepting_state;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer( yyscanner ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yyg->yy_did_buffer_switch_on_eof = 0;

				if ( yywrap( yyscanner ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yyg->yy_c_buf_p = yyg->yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yyg->yy_c_buf_p =
					yyg->yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yyg->yy_c_buf_p =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars];

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = yyg->yytext_ptr;
	int number_to_move, i;
	int ret_val;

	if ( yyg->yy_c_buf_p > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yyg->yy_c_buf_p - yyg->yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yyg->yy_c_buf_p - yyg->yytext_ptr - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) (yyg->yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2) , yyscanner );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yyg->yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			yyg->yy_n_chars, num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	if ( yyg->yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  , yyscanner);
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yyg->yy_n_chars + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = yyg->yy_n_chars + number_to_move + (yyg->yy_n_chars >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size , yyscanner );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	yyg->yy_n_chars += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yyg->yytext_ptr = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (yyscan_t yyscanner)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	yy_current_state = yyg->yy_start;
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = yyg->yytext_ptr + YY_MORE_ADJ; yy_cp < yyg->yy_c_buf_p; ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yyg->yy_last_accepting_state = yy_current_state;
			yyg->yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 348 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state , yyscan_t yyscanner)
{
	int yy_is_jam;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner; /* This var may be unused depending upon options. */
	char *yy_cp = yyg->yy_c_buf_p;

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yyg->yy_last_accepting_state = yy_current_state;
		yyg->yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 348 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 347);

	(void)yyg;
	return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp , yyscan_t yyscanner)
{
	char *yy_cp;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    yy_cp = yyg->yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yyg->yy_hold_char;

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = yyg->yy_n_chars + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			yyg->yy_n_chars = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	yyg->yytext_ptr = yy_bp;
	yyg->yy_hold_char = *yy_cp;
	yyg->yy_c_buf_p = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (yyscan_t yyscanner)
#else
    static int input  (yyscan_t yyscanner)
#endif

{
	int c;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	*yyg->yy_c_buf_p = yyg->yy_hold_char;

	if ( *yyg->yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yyg->yy_c_buf_p < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			/* This was really a NUL. */
			*yyg->yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = (int) (yyg->yy_c_buf_p - yyg->yytext_ptr);
			++yyg->yy_c_buf_p;

			switch ( yy_get_next_buffer( yyscanner ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin , yyscanner);

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( yyscanner ) )
						return 0;

					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput(yyscanner);
#else
					return input(yyscanner);
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yyg->yy_c_buf_p = yyg->yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yyg->yy_c_buf_p;	/* cast for 8-bit char's */
	*yyg->yy_c_buf_p = '\0';	/* preserve yytext */
	yyg->yy_hold_char = *++yyg->yy_c_buf_p;

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');
	if ( YY_CURRENT_BUFFER_LVALUE->yy_at_bol )
		
    do{ yylineno++;
        yycolumn=0;
    }while(0)
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * @param yyscanner The scanner object.
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack (yyscanner);
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE , yyscanner);
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file , yyscanner);
	yy_load_buffer_state( yyscanner );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * @param yyscanner The scanner object.
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack (yyscanner);
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( yyscanner );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yyg->yy_did_buffer_switch_on_eof = 1;
}

static void yy_load_buffer_state  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	yyg->yytext_ptr = yyg->yy_c_buf_p = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	yyg->yy_hold_char = *yyg->yy_c_buf_p;
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * @param yyscanner The scanner object.
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state ) , yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2) , yyscanner );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file , yyscanner);

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * @param yyscanner The scanner object.
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf , yyscanner );

	yyfree( (void *) b , yyscanner );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file , yyscan_t yyscanner)

{
	int oerrno = errno;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	yy_flush_buffer( b , yyscanner);

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * @param yyscanner The scanner object.
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( yyscanner );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  @param yyscanner The scanner object.
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack(yyscanner);

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		yyg->yy_buffer_stack_top++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( yyscanner );
	yyg->yy_did_buffer_switch_on_eof = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  @param yyscanner The scanner object.
 */
void yypop_buffer_state (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER , yyscanner);
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if (yyg->yy_buffer_stack_top > 0)
		--yyg->yy_buffer_stack_top;

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( yyscanner );
		yyg->yy_did_buffer_switch_on_eof = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (yyscan_t yyscanner)
{
	yy_size_t num_to_alloc;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if (!yyg->yy_buffer_stack) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		yyg->yy_buffer_stack = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset(yyg->yy_buffer_stack, 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		yyg->yy_buffer_stack_max = num_to_alloc;
		yyg->yy_buffer_stack_top = 0;
		return;
	}

	if (yyg->yy_buffer_stack_top >= (yyg->yy_buffer_stack_max) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = yyg->yy_buffer_stack_max + grow_size;
		yyg->yy_buffer_stack = (struct yy_buffer_state**)yyrealloc
								(yyg->yy_buffer_stack,
								num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset(yyg->yy_buffer_stack + yyg->yy_buffer_stack_max, 0, grow_size * sizeof(struct yy_buffer_state*));
		yyg->yy_buffer_stack_max = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state ) , yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b , yyscanner );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr , yyscan_t yyscanner)
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) , yyscanner);
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n , yyscanner );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n , yyscanner);
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;
	fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = yyg->yy_hold_char; \
		yyg->yy_c_buf_p = yytext + yyless_macro_arg; \
		yyg->yy_hold_char = *yyg->yy_c_buf_p; \
		*yyg->yy_c_buf_p = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the user-defined data for this scanner.
 * @param yyscanner The scanner object.
 */
YY_EXTRA_TYPE yyget_extra  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyextra;
}

/** Get the current line number.
 * @param yyscanner The scanner object.
 */
int yyget_lineno  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yylineno;
}

/** Get the current column number.
 * @param yyscanner The scanner object.
 */
int yyget_column  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yycolumn;
}

/** Get the input stream.
 * @param yyscanner The scanner object.
 */
FILE *yyget_in  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyin;
}

/** Get the output stream.
 * @param yyscanner The scanner object.
 */
FILE *yyget_out  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyout;
}

/** Get the length of the current token.
 * @param yyscanner The scanner object.
 */
int yyget_leng  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyleng;
}

/** Get the current token.
 * @param yyscanner The scanner object.
 */

char *yyget_text  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yytext;
}

/** Set the user-defined data. This data is never touched by the scanner.
 * @param user_defined The data to be associated with this scanner.
 * @param yyscanner The scanner object.
 */
void yyset_extra (YY_EXTRA_TYPE  user_defined , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyextra = user_defined ;
}

/** Set the current line number.
 * @param _line_number line number
 * @param yyscanner The scanner object.
 */
void yyset_lineno (int  _line_number , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* lineno is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           YY_FATAL_ERROR( "yyset_lineno called with no buffer" );
    
    yylineno = _line_number;
}

/** Set the current column.
 * @param _column_no column number
 * @param yyscanner The scanner object.
 */
void yyset_column (int  _column_no , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* column is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           YY_FATAL_ERROR( "yyset_column called with no buffer" );
    
    yycolumn = _column_no;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * @param yyscanner The scanner object.
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyin = _in_str ;
}

void yyset_out (FILE *  _out_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyout = _out_str ;
}

int yyget_debug  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yy_flex_debug;
}

void yyset_debug (int  _bdebug , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yy_flex_debug = _bdebug ;
}

/* Accessor methods for yylval and yylloc */

YYSTYPE * yyget_lval  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yylval;
}

void yyset_lval (YYSTYPE *  yylval_param , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yylval = yylval_param;
}

YYLTYPE *yyget_lloc  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yylloc;
}
    
void yyset_lloc (YYLTYPE *  yylloc_param , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yylloc = yylloc_param;
}
    
/* User-visible API */

/* yylex_init is special because it creates the scanner itself, so it is
 * the ONLY reentrant function that doesn't take the scanner as the last argument.
 * That's why we explicitly handle the declaration, instead of using our macros.
 */
int yylex_init(yyscan_t* ptr_yy_globals)
{
    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }

    *ptr_yy_globals = (yyscan_t) yyalloc ( sizeof( struct yyguts_t ), NULL );

    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }

    /* By setting to 0xAA, we expose bugs in yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));

    return yy_init_globals ( *ptr_yy_globals );
}

/* yylex_init_extra has the same functionality as yylex_init, but follows the
 * convention of taking the scanner as the last argument. Note however, that
 * this is a *pointer* to a scanner, as it will be allocated by this call (and
 * is the reason, too, why this function also must handle its own declaration).
 * The user defined value in the first argument will be available to yyalloc in
 * the yyextra field.
 */
int yylex_init_extra( YY_EXTRA_TYPE yy_user_defined, yyscan_t* ptr_yy_globals )
{
    struct yyguts_t dummy_yyguts;

    yyset_extra (yy_user_defined, &dummy_yyguts);

    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }

    *ptr_yy_globals = (yyscan_t) yyalloc ( sizeof( struct yyguts_t ), &dummy_yyguts );

    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }

    /* By setting to 0xAA, we expose bugs in
    yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));

    yyset_extra (yy_user_defined, *ptr_yy_globals);

    return yy_init_globals ( *ptr_yy_globals );
}

static int yy_init_globals (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    yyg->yy_buffer_stack = NULL;
    yyg->yy_buffer_stack_top = 0;
    yyg->yy_buffer_stack_max = 0;
    yyg->yy_c_buf_p = NULL;
    yyg->yy_init = 0;
    yyg->yy_start = 0;

    yyg->yy_start_stack_ptr = 0;
    yyg->yy_start_stack_depth = 0;
    yyg->yy_start_stack =  NULL;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER , yyscanner );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state(yyscanner);
	}

	/* Destroy the stack itself. */
	yyfree(yyg->yy_buffer_stack , yyscanner);
	yyg->yy_buffer_stack = NULL;

    /* Destroy the start condition stack. */
        yyfree( yyg->yy_start_stack , yyscanner );
        yyg->yy_start_stack = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( yyscanner);

    /* Destroy the main struct (reentrant only). */
    yyfree ( yyscanner , yyscanner );
    yyscanner = NULL;
    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;

	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s , yyscan_t yyscanner)
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;
	return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;

	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr , yyscan_t yyscanner)
{
	struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	(void)yyg;
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 284 "beancount/parser/lexer.l"


yyscan_t yylex_new(void)
{
    yyscan_t scanner;
    yyextra_t* extra;

    extra = malloc(sizeof(*extra));
    if (!extra)
        return NULL;

    extra->filename = NULL;

    yylex_init_extra(extra, &scanner);
    if (!scanner) {
        free(extra);
        return NULL;
    }

    PyDateTime_IMPORT;
    PyDecimal_IMPORT;

    return scanner;
}

yyscan_t yylex_free(yyscan_t scanner)
{
    yyextra_t* extra = yyget_extra(scanner);

    Py_XDECREF(extra->filename);
    free(extra);

    Py_XDECREF(yyget_in(scanner));
    yylex_destroy(scanner);

    return NULL;
}

/* yyrestart() does not reset the scanner back to INITIAL state and
 * Flex does not provide a way of doing so outside a scanner
 * rule. This function does just that accessing Flex internals. */
static void yybegin(yyscan_t scanner)
{
    struct yyguts_t* yyg = (struct yyguts_t*)scanner;
    BEGIN(INITIAL);
}

void yylex_initialize(PyObject* file, PyObject* filename, int lineno, const char* encoding, yyscan_t scanner)
{
    yyextra_t* extra = yyget_extra(scanner);

    if (!filename || filename == Py_None) {
        /* If a filename has not been specified, get it from the 'name'
	 * attribute of the input file object. */
        filename = PyObject_GetAttrString(file, "name");
        if (!filename) {
	    /* No 'name' attribute. */
	    PyErr_Clear();
            /* Use the empty string. */
            filename = PyUnicode_FromString("");
        }
    } else {
        Py_INCREF(filename);
    }

    Py_XDECREF(extra->filename);
    extra->filename = filename;

    extra->encoding = encoding ? encoding : "utf-8";

    Py_XDECREF(yyget_in(scanner));
    Py_INCREF(file);
    yyrestart((void *)file, scanner);
    yybegin(scanner);

    yyset_lineno(lineno, scanner);
}

/* Build and accumulate an error on the builder object. */
void build_lexer_error(YYLTYPE* loc, PyObject* builder, const char* format, ...)
{
    PyObject* error;
    PyObject* rv;
    va_list va;

    va_start(va, format);
    error = PyUnicode_FromFormatV(format, va);
    va_end(va);

    if (!error) {
        return;
    }

    /* Build and accumulate a new error object. {27d1d459c5cd} */
    rv = PyObject_CallMethod(builder, "build_lexer_error", "OiO",
                             loc->file_name, loc->first_line, error);

    Py_XDECREF(rv);
    Py_XDECREF(error);
}

void build_lexer_error_from_exception(YYLTYPE* loc, PyObject* builder)
{
    PyObject* type;
    PyObject* value;
    PyObject* traceback;

    PyErr_Fetch(&type, &value, &traceback);
    PyErr_NormalizeException(&type, &value, &traceback);

    build_lexer_error(loc, builder, "%s: %S", PyExceptionClass_Name(type), value);

    Py_XDECREF(type);
    Py_XDECREF(value);
    Py_XDECREF(traceback);
}

int pyfile_read_into(PyObject *file, char *buf, size_t max_size)
{
    PyObject* dest = NULL;
    PyObject* read = NULL;
    int ret = 0;

    // Note: Eventually we ought to allocate this once in the parser state and
    // avoid reallocating this on every block read.
    dest = PyMemoryView_FromMemory(buf, max_size, PyBUF_WRITE);
    if (!dest) {
	goto error;
    }

    read = PyObject_CallMethod(file, "readinto", "O", dest);
    if (!read) {
	goto error;
    }

    ret = PyLong_AsSize_t(read);
    if (PyErr_Occurred()) {
	ret = 0;
    }

error:
    Py_XDECREF(dest);
    Py_XDECREF(read);
    return ret;
}

